// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppSNAP.h"
#include <Rcpp.h>

using namespace Rcpp;

// DefaultConstructor
int DefaultConstructor();
RcppExport SEXP _RcppSNAP_DefaultConstructor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(DefaultConstructor());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppSNAP_DefaultConstructor", (DL_FUNC) &_RcppSNAP_DefaultConstructor, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppSNAP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
